version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      - echo "Zipping app.py from the lambda folder..."
      - cd lambda && zip ../function.zip app.py && cd ..

artifacts:
  files:
    - function.zip
