version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      - echo "Zipping Lambda function"
      - cd lambda && zip ../function.zip app.py && cd ..
  post_build:
    commands:
      - echo "Updating Lambda function"
      - aws lambda update-function-code --function-name TaskApiFunction --zip-file fileb://function.zip
